"""initial

Revision ID: 0466ace1fe19
Revises: 
Create Date: 2023-09-08 18:11:13.991372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0466ace1fe19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'update_at',
               existing_type=sa.SMALLINT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('userchats', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('userchats', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('userchats', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('userchats', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chats', 'update_at',
               existing_type=sa.DateTime(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
